import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <div className="w-full bg-black py-6" >
          <h1 className="text-4xl font-bold text-center text-white">Geekle</h1>
        </div>
        {children}
        </body>
    </html>
  )
}
